name: test-main-branch
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - API.py
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - name: run python program
        run: python API_Code/FastAPI.py
