name: test-main-branch
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - API.py
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          node-version: '24'
      - run: npm install -g bats
      - run: bats -v
