name: test-main-branch
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile student.cpp
        run: g++ menu.cpp studentlist.cpp student.cpp

      - name: Run the program
        run: timeout 10 ./a.out << EOF
             I
             test3.txt
             Q
             EOF
